

# ディメンション生成のチェック
  data modify storage menu: DimensionGenerated set value 0b
  execute store success storage menu: DimensionGenerated byte 1 in menu: run help help .
  execute unless data storage menu: {DimensionGenerated:1b} run tellraw @a {"text":"[Menu] WARNING: ディメンションが未生成のため、一部機能が動作しません。 フル機能の使用にはワールドの再読み込みが必要です。","color":"#ffcc00"}

# 追加ディメンションに対してforceloadとshulkerboxの設置を行う
  execute if data storage menu: {DimensionGenerated:1b} in menu: unless loaded 0 0 0 run forceload add -1 -1 1 1
  execute if data storage menu: {DimensionGenerated:1b} in menu: unless block 0 0 0 shulker_box run setblock 0 0 0 shulker_box


# スコア
  scoreboard objectives add MenuPage dummy
  scoreboard objectives add MenuButton trigger

# ダイアログのメニューデータを作成
  # 初期化
    data modify storage menu: database set value []
  # loadから実行してますフラグ
    data modify storage menu: is_load set value 1b
  function #menu:_database
  # loadから実行してますフラグ解除
    data remove storage menu: is_load
# ↑で作成したデータに番号を割り当てておく
# ついでにinvertもできてオトク
  scoreboard players set # MenuButton 0
  data modify storage menu: macro._ set value []
  execute if data storage menu: database[-1] run function menu:_database/1.loop
  data modify storage menu: database set from storage menu: macro._
# -1番にcloseを割り当て
# Page概念はこいつには無関係なので与えない
  data modify storage menu: database append value {ButtonNumber:-1,type:"exit_button",label:{text:"閉じる"},action:{type:"dialog_close"}}

# 属性タグを付与
execute if data storage menu: database[{type:"body_text"}] run data modify storage menu: database[{type:"body_text"}].attribute set value "body"
execute if data storage menu: database[{type:"body_item"}] run data modify storage menu: database[{type:"body_item"}].attribute set value "body"
execute if data storage menu: database[{type:"input_bool"}] run data modify storage menu: database[{type:"input_bool"}].attribute set value "inputs"
execute if data storage menu: database[{type:"input_num"}] run data modify storage menu: database[{type:"input_num"}].attribute set value "inputs"
execute if data storage menu: database[{type:"input_select"}] run data modify storage menu: database[{type:"input_select"}].attribute set value "inputs"
execute if data storage menu: database[{type:"input_text"}] run data modify storage menu: database[{type:"input_text"}].attribute set value "inputs"



